doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
            User:
                type: yml
                prefix: 'App\Domain\User\Model'
                dir: '%kernel.root_dir%/../src/Infrastructure/UserBundle/Resources/config/persistence'
                is_bundle: false
            BlogPost:
              type: yml
              prefix: 'App\Domain\BlogPost\Model'
              dir: '%kernel.root_dir%/../src/Infrastructure/BlogPostBundle/Resources/config/persistence'
              is_bundle: false
            Tag:
              type: yml
              prefix: 'App\Domain\Tag\Model'
              dir: '%kernel.root_dir%/../src/Infrastructure/TagBundle/Resources/config/persistence'
              is_bundle: false
#            App:
#                type: annotation
#                prefix: 'App\Domain\User\Model'
#                dir: '%kernel.project_dir%/src/Domain/User/Model'
#                is_bundle: false
