App\Domain\Tag\Model\Tag:
  type: entity
  repositoryClass: App\Infrastructure\TagBundle\Repository\DoctrineTagRepository
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      column: id
      generator:
        strategy: IDENTITY
  fields:
    name:
      type: string
      scale: 0
      length: 255
      unique: true
      nullable: false
      precision: 0
    createdAt:
      type: datetime
      scale: 0
      unique: false
      nullable: false
      precision: 0
    updatedAt:
      type: datetime
      scale: 0
      unique: false
      nullable: false
      precision: 0
  manyToOne:
    blogPost:
      targetEntity: App\Domain\BlogPost\Model\BlogPost
      joinColumn:
        name: blogPost
        nullable: false
        onDelete: CASCADE
      cascade:
        - all

