App\Domain\User\Model\User:
  type: entity
  table: users
  repositoryClass: App\Infrastructure\UserBundle\Repository\DoctrineUserRepository
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      column: id
      generator:
        strategy: IDENTITY
  fields:
    email:
      type: string
      scale: 0
      length: 255
      unique: true
      nullable: false
      precision: 0
    username:
      type: string
      scale: 0
      length: 255
      unique: false
      nullable: false
      precision: 0
    password:
      type: string
      scale: 0
      length: 64
      unique: false
      nullable: false
      precision: 0
    roles:
      type: json
      scale: 0
      nullable: false
      precision: 0
  oneToMany:
    blogPosts:
      targetEntity: App\Domain\BlogPost\Model\BlogPost
      mappedBy: user


  lifecycleCallbacks: {  }
