App\Domain\BlogPost\Model\BlogPost:
  type: entity
  repositoryClass: App\Infrastructure\BlogPostBundle\Repository\DoctrineBlogPostRepository
  id:
    id:
      type: integer
      scale: 0
      length: null
      unique: false
      nullable: false
      precision: 0
      id: true
      column: id
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
      scale: 0
      length: 255
      unique: true
      nullable: false
      precision: 0
    content:
      type: text
      scale: 0
      unique: false
      nullable: false
      precision: 0
    slug:
      type: string
      scale: 0
      length: 255
      unique: true
      nullable: false
      precision: 0
    createdAt:
      type: datetime
      scale: 0
      unique: false
      nullable: false
      precision: 0
    updatedAt:
      type: datetime
      scale: 0
      unique: false
      nullable: false
      precision: 0
  manyToOne:
    user:
      targetEntity: App\Domain\User\Model\User
      joinColumn:
        name: user
        nullable: false
        onDelete: CASCADE
      cascade:
        - all
  oneToMany:
    tags:
      targetEntity: App\Domain\Tag\Model\Tag
      mappedBy: blogPost
      joinColumn:
        nullable: true

